# Generated by Django 5.2 on 2025-04-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_email', models.EmailField(max_length=254)),
                ('stu_contact', models.IntegerField()),
                ('stu_dob', models.DateField()),
                ('stu_gender', models.CharField(max_length=50)),
                ('stu_pass', models.CharField(max_length=50)),
            ],
        ),
    ]
